[package]
name = "operad"
version = "4.0.0"
edition = "2021"
license = "MIT"

[lib]
name = "operad"
path = "src/lib.rs"

[features]
default = []
egui = ["dep:egui"]
egui-renderer-compat = ["egui"]
wgpu = ["dep:wgpu", "dep:pollster", "dep:glyphon"]
text-cosmic = ["dep:cosmic-text"]
widgets = []
audit = []

[dependencies]
cosmic-text = { version = "0.14.2", optional = true }
egui = { version = "0.33.3", optional = true }
glyphon = { version = "0.9.0", optional = true }
pollster = { version = "0.4.0", optional = true }
taffy = "0.10.1"
wgpu = { version = "25.0.1", optional = true, features = ["wgsl"] }
